### PR TITLE
improve data loading

### PR DESCRIPTION
**Pull request by erezh31**

### CODE REVIEW

**Comment by erezh31** [comment]
** Test load full data before merge **

**Comment by atalyaalon** [comment]
@erezh31 , please take a look at the ci results, there are some unused imports.
In addition, why did you take off marker's data, link yishuv_symbol, geo_location, etc?

**Comment by erezh31** [comment]
@atalyaalon removed unused imports.
I didn't removed - probably my branch was not up-to-date somehow... now it's back

**Comment by atalyaalon** [comment]
@erezh31 Thank you. It's still uncompetible to python 3 (due to xrange).

**Pull request merged**
