### PR TITLE
Add suburban junction query results to news-flash API

### PR DESCRIPTION
**Pull request by afedj**
Currently when querying the news-flash API with query parameter `resolution=suburban_road`,
the query returns with news-flash results where the resolution is suburban_road and the road_segment isn't empty.

This change modified that behavior so that when querying for suburban_road the returned results are
any news-flash where the resolution is either suburban_road OR suburban_junction and a road_segment exists.

### CODE REVIEW

**Comment by ziv17** [comment]
Hi @atalyaalon , @MichalOren ,
Is there a difference in the accidents that are included in infographics-data of the following two locations?
1 - `resolution=suburban_road`, location fields: `road_segment`, `road1`, and
2 - `resolution=suburban_junction`, location fields: `road_segment`, `road1`, `road2`?

**Comment by MichalOren** [comment]
Hi @ziv17 i am not familer with this change. @atalyaalon?

**Comment by ziv17** [comment]
Hi @atalyaalon,  sure. What accidents are included in this resolution?

**Comment by atalyaalon** [comment]
> Hi @atalyaalon , @MichalOren , Is there a difference in the accidents that are included in infographics-data of the following two locations? 1 - `resolution=suburban_road`, location fields: `road_segment`, `road1`, and 2 - `resolution=suburban_junction`, location fields: `road_segment`, `road1`, `road2`?

just to make sure - no - we want use all as suburban resolution, and use ONLY road1 and road segment when creating infographics.

**Comment by ziv17** [comment]
Hi @atalyaalon 
You mean that infographics of news-flashes with `resolution=suburban_junction` and location fields: `road_segment`, `road1`, `road2` should behave as if the resolution is `suburban_road` and `road2` is empty?
If so, why not set this resolution in the news-flash?

**Comment by atalyaalon** [comment]
@ziv17 I agree. Let's handle this in the NewsFlash level. Seems like it requires removing [2 rows here - 102-103](https://github.com/hasadna/anyway/blob/0fd4f869f48476bfb85097435c82ab097486584c/anyway/parsers/location_extraction.py#L93)
I think we should remove 100-101 since we don't use urban intersection resolution as well. What do you think?

**Pull request closed without merging**
