### PR TITLE
Fixed #356 - Moved years.js creation to main.py run

### LINKED ISSUE #356: Keep years.js out of version control
`statis/js/years.js` is generated when running `process.py`. Therefore, it should be ignored by Git and kept in a special location.

### PR DESCRIPTION
**Pull request by omerxx**
Fixed #356 - `years.js` is now created with `main.py` run.

It goes through markers table and takes distinct years making it a json
* It adds 6-7 sec to main.py but it works great
* Could be little disturbing for development but most of us use the example file so the DB is very small and it shouldn't be felt at all

### CODE REVIEW

**Comment by omerxx** [comment]
@danielhers does this fix the issue?

**Comment by danielhers** [comment]
The file years.js should be removed and ignored since it's generated.
There should be a way to query the distinct years from the DB. If not using
the ORM then as explicit SQL. It should take much less than 6 seconds.

**Comment by omerxx** [comment]
@danielhers you were right, explicitly selecting the substring does it in less then a second.
I've changed it.

Should we also add this to `.gitignore`?

**Comment by danielhers** [comment]
Great, I'm glad you found a way to do it in the DB.

Yes, `years.js` should be deleted from Git and added to `.gitignore`.

Why did you leave the function in `process.py` if it's only used in `main.py`? I think it should be defined there too.

**Comment by omerxx** [comment]
Seemed more appropriate at the beginning, I'll move it 


ב-10 ביול 2015, בשעה 20:09, Daniel Hershcovich <notifications@github.com> כתב/ה:

**Comment by omerxx** [comment]
Moved `create_years_list()` to `main.py`

**Pull request merged**
