### PR TITLE
Fix #396 default year range

### LINKED ISSUE #396: Change default date range to 2014
Now that 2014 data is in the DB, users should see this data by default

Date Range

### PR DESCRIPTION
**Pull request by omerxx**
Changed the default range to present 2014 accidents

### CODE REVIEW

**Comment by danielhers** [comment]
Why did you close it?

**Comment by omerxx** [comment]
It constantly pushes your fix in main.py too
Any idea why?

**Comment by danielhers** [comment]
I don't know... It also looks as if I authored your commit.
Try creating a new updated branch and apply the change there.

**Comment by omerxx** [comment]
I noticed that too. I tried another once or twice but it kept pushing your fix.
Thought maybe git needs time to update and I'll try again with a new one

**Pull request closed without merging**
