### PR TITLE
merge dev into master

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@OriHoch this merge into master includes https://github.com/hasadna/anyway/pull/2013
You wrote: "deployment needs to be done manually because we don't do continuous deployment of the DB"
What does this mean? Should you deploy the DB after this merge?

**Comment by atalyaalon** [comment]
@OriHoch Also - does this required redeployment of DB in dev, now that it's merged into dev?

**Comment by OriHoch** [comment]
yes, I need to deploy it after it's merged, I will deploy to dev as well

**Comment by OriHoch** [comment]
@atalyaalon we don't have db backup from dev, so no need to deploy it there

after you merge it to masdter I can deploy to prod

**Review by OriHoch — COMMENTED** [review]
can't review this PR, I wrote comments regarding the db backup

**Comment by atalyaalon** [comment]
@OriHoch I merged to master

**Comment by OriHoch** [comment]
deployed

**Pull request merged**
