### PR TITLE
Reduce anyway image size (#1325)

### PR DESCRIPTION
**Pull request by dimakuz**
This patch reduces anyway image size by switching to a multistage build.
virtualenv is created in a builder container that has all the required
build dependencies installed. Then the env is copied into a slimmer
container based on the same distro.

### CODE REVIEW

**Comment by dimakuz** [comment]
venv is still quite big at over 260mb

```
root@4dc513f50ac2:/venv3/lib/python3.7/site-packages# du -hs * | sort -hr
46M	pandas
29M	numpy.libs
29M	babel
23M	numpy
16M	pyproj
14M	pyproj.libs
12M	google
11M	lxml
11M	flask_admin
9.6M	pip
9.4M	sqlalchemy
4.4M	newrelic
3.5M	passlib
3.0M	graphql
2.8M	pytz
2.6M	openpyxl
2.3M	setuptools
2.2M	rx
2.0M	werkzeug
1.6M	pyasn1_modules
1.5M	alembic
1.3M	wtforms
1.3M	oauthlib
1.2M	graphene
1004K	webassets
952K	pkg_resources
936K	jinja2
924K	chardet
860K	pyasn1
828K	bs4
808K	sendgrid
800K	urllib3
760K	_brotli.cpython-37m-x86_64-linux-gnu.so
732K	dateutil
660K	xlrd
656K	flask
632K	gunicorn
592K	mako
580K	psycopg2
576K	click
520K	flask_security
516K	idna
472K	aniso8601
404K	requests
332K	graphene_sqlalchemy
332K	__pycache__
312K	certifi
308K	rsa
296K	tweepy
276K	graphql_relay
276K	geographiclib
276K	attr
224K	soupsieve
216K	googlemaps
200K	wheel
196K	requests_oauthlib
192K	promise
180K	examples
168K	pandas-1.0.3.dist-info
168K	geoalchemy2
160K	feedparser.py
144K	rauth
140K	numpy-1.18.4.dist-info
132K	flask_login
128K	flask_wtf
124K	pytz-2020.1.dist-info
124K	itsdangerous
116K	flask_sqlalchemy
100K	cachetools
96K	et_xmlfile
96K	Babel-2.8.0.dist-info
88K	pip-20.1.1.dist-info
88K	markupsafe
84K	fuzzywuzzy
84K	flask_cors
84K	blinker
72K	googlesearch
72K	Flask_Admin-1.5.6.dist-info
68K	urllib3-1.25.9.dist-info
68K	newrelic-5.12.1.141.dist-info
68K	flask_babel
68K	Rx-1.6.1.dist-info
64K	graphql_core-2.3.2.dist-info
60K	flask_babelex
60K	SQLAlchemy-1.3.17.dist-info
56K	setuptools-47.3.0.dist-info
52K	sendgrid-6.3.1.dist-info
52K	python_http_client
52K	pyproj-2.6.1.post1.dist-info
52K	openpyxl-3.0.3.dist-info
52K	fuzzywuzzy-0.18.0.dist-info
48K	rcssmin-1.0.6.dist-info
48K	passlib-1.7.2.dist-info
48K	graphene-2.1.8.dist-info
48K	googleapis_common_protos-1.52.0.dist-info
48K	google_cloud_language-1.3.0.dist-info
44K	webassets-2.0.dist-info
44K	singledispatch-3.4.0.3.dist-info
44K	pyasn1_modules-0.2.8.dist-info
44K	protobuf-3.12.2.dist-info
44K	googlemaps-4.4.0.dist-info
44K	google_cloud_translate-2.0.1.dist-info
44K	google_cloud_storage-1.28.1.dist-info
44K	google_auth-1.17.2.dist-info
44K	google_api_core-1.17.0.dist-info
44K	aniso8601-7.0.0.dist-info
44K	alembic-1.4.2.dist-info
40K	pkg_resources-0.0.0.dist-info
40K	oauthlib-3.1.0.dist-info
40K	jdcal-1.4.1.dist-info
40K	google_resumable_media-0.5.1.dist-info
40K	google_cloud_core-1.3.0.dist-info
40K	chardet-3.0.4.dist-info
40K	Werkzeug-0.16.1.dist-info
40K	PySocks-1.7.1.dist-info
40K	Flask_Security-3.0.0.dist-info
36K	six.py
36K	requests_oauthlib-1.3.0.dist-info
36K	python_dateutil-2.8.1.dist-info
36K	pyasn1-0.4.8.dist-info
36K	lxml-4.5.1.dist-info
36K	idna-2.9.dist-info
36K	gunicorn-20.0.4.dist-info
36K	graphql_relay-2.0.1.dist-info
36K	attrs-19.3.0.dist-info
36K	Mako-1.1.3.dist-info
36K	Flask-1.1.2.dist-info
32K	wheel-0.34.2.dist-info
32K	tweepy-3.8.0.dist-info
32K	soupsieve-2.0.1.dist-info
32K	socks.py
32K	rsa-4.6.dist-info
32K	requests-2.23.0.dist-info
32K	rauth-0.7.3.dist-info
32K	python_editor-1.0.4.dist-info
32K	psycopg2-2.8.5.dist-info
32K	promise-2.3.dist-info
32K	graphene_sqlalchemy-2.2.2.dist-info
32K	google-2.0.3.dist-info
32K	cachetools-4.1.0.dist-info
32K	blinker-1.4.dist-info
32K	WTForms-2.2.1.dist-info
32K	Jinja2-2.11.2.dist-info
32K	GeoAlchemy2-0.8.2.dist-info
32K	Flask_Cors-3.0.8.dist-info
32K	Flask_Compress-1.5.0.dist-info
32K	Flask_Assets-2.0.dist-info
28K	xlrd-1.2.0.dist-info
28K	speaklater-1.3.dist-info
28K	six-1.15.0.dist-info
28K	python_http_client-3.2.7.dist-info
28K	itsdangerous-1.1.0.dist-info
28K	geographiclib-1.50.dist-info
28K	feedparser-5.2.1.dist-info
28K	click-7.1.2.dist-info
28K	certifi-2020.4.5.2.dist-info
28K	beautifulsoup4-4.8.2.dist-info
28K	MarkupSafe-1.1.1.dist-info
28K	Flask_WTF-0.14.3.dist-info
28K	Flask_SQLAlchemy-2.4.1.dist-info
28K	Flask_Mail-0.9.1.dist-info
28K	Flask_Login-0.5.0.dist-info
28K	Flask_BabelEx-0.9.4.dist-info
28K	Flask_Babel-1.0.0.dist-info
24K	python_geohash-0.8.5.dist-info
24K	google_cloud-0.34.0.dist-info
24K	et_xmlfile-1.0.1.dist-info
24K	_geohash.cpython-37m-x86_64-linux-gnu.so
24K	Flask_Principal-0.4.0.dist-info
24K	Brotli-1.0.7.dist-info
20K	flask_mail.py
20K	flask_assets.py
20K	_rcssmin.cpython-37m-x86_64-linux-gnu.so
16K	rcssmin.py
16K	jdcal.py
16K	geohash.py
16K	flask_principal.py
12K	singledispatch.py
8.0K	speaklater.py
8.0K	singledispatch_helpers.py
8.0K	flask_compress.py
4.0K	sockshandler.py
4.0K	quadtree.py
4.0K	protobuf-3.12.2-py3.7-nspkg.pth
4.0K	jpiarea.py
4.0K	jpgrid.py
4.0K	googleapis_common_protos-1.52.0-py3.8-nspkg.pth
4.0K	google_resumable_media-0.5.1-py3.8-nspkg.pth
4.0K	google_cloud_translate-2.0.1-py3.8-nspkg.pth
4.0K	google_cloud_storage-1.28.1-py3.8-nspkg.pth
4.0K	google_cloud_language-1.3.0-py3.6-nspkg.pth
4.0K	google_cloud_core-1.3.0-py3.8-nspkg.pth
4.0K	google_auth-1.17.2-py3.8-nspkg.pth
4.0K	google_api_core-1.17.0-py3.8-nspkg.pth
4.0K	editor.py
4.0K	easy_install.py
4.0K	brotli.py
```

**Comment by atalyaalon** [comment]
@dimakuz please solve conflicts
Afterwards, @assafdayan @OriHoch please review

**Comment by idosavion** [comment]
everything is clear and the PR looks great! why are you replacing YUICompressor? It's less than 1MB in pip? Am I missing something?

**Comment by dimakuz** [comment]
@OriHoch it went down from 1.37GB to 423MB

**Comment by dimakuz** [comment]
@idosavion YUICompressor requires Java runtime which pulls about 200MB

**Pull request merged**
