### PR TITLE
Newsflash none only

### PR DESCRIPTION
**Pull request by carmelp16**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@carmelp16 please fix pylint test

**Comment by atalyaalon** [comment]
Other than that looks good :) @ziv17 any thoughts?

**Comment by ziv17** [comment]
The `insert_new_newsflash()` is not needed any more, together with the cache per news_flash. We only use infographics per location now. I will remove it in a future PR.

**Comment by ziv17** [comment]
> Other than that looks good :) @ziv17 any thoughts?

Very nice. Elegant test!

**Pull request merged**
