### PR TITLE
Fix key duplication error while inserting values to streets table

### PR DESCRIPTION
**Pull request by ziv17**

### CODE REVIEW

**Review by atalyaalon — CHANGES_REQUESTED** [review]
@ziv17 did you encounter such cases? that in the same streets file there is inconsistency?

Regarding insertion to table - I'm not sure we want to delete all streets and then insert all items. Perhaps only update? (Since every year and every provider code we can get different streets and not all relevant streets).

In this case we'll have to decide what to do with inconsistencies - as the one you found - I suggest using latest mapping per yishuv, street keys, what do you say?

**Comment by ziv17** [comment]
> @ziv17 did you encounter such cases? that in the same streets file there is inconsistency?
> 
> Regarding insertion to table - I'm not sure we want to delete all streets and then insert all items. Perhaps only update? (Since every year and every provider code we can get different streets and not all relevant streets).
> 
> In this case we'll have to decide what to do with inconsistencies - as the one you found - I suggest using latest mapping per yishuv, street keys, what do you say?

- I did encountered duplication, due to a bug, that cause the table write to fail. 
- I agree regarding not deleting existing content of streets table. I will add code that only adds streets.
- In case of inconsistencies, code takes latest mapping.

**Comment by ziv17** [comment]
@atalyaalon I preferred reading the data, integrating the new data with the existing in memory, and then deleting and inserting all the data, over keeping two lists, of new and updated items, and then insert / update them. It is simpler code, and the amount of data is not big.

**Review by BarVolunteering — APPROVED** [review]
Good work!

**Pull request merged**
