### PR TITLE
Implement issue #1579: motorcycle road vs entire country accident ratio

### LINKED ISSUE #1579: Widget: motorcycle_accidents_vs_all_accidents
**Name**
Query for severe and fatal motorcycle accidents VS other accidents in a specific road vs all of the interurban roads 

**Title**
תאונות אופנועים קשות וקטלניות בכביש __ בהשוואה לכל הארץ
(שם הכותרת משתנה כתלות במספר כביש)

**Visualization**
@MichalOren please attach :) 

**Visualization explanation**
Visualization contains 2 bar graphs (for the specific road and for all of Israel interurban roads)
Each bar is a stacked bar completing to 100% containing the the percentage of severe and fatal accidents with motorcycles and the rest - all other severe and fatal accidents.

**Use case**
When the percentage of motorcycle accidents in the specific road is greater than 1.5 times the percentage of the motorcycle accidents in all of the roads (for example, if all interurban roads have a 20% of motorcycle severe and fatal accidents, infographics will be presented if the specific road has at least 30% of motorcycle accidents)

**SQL query**
See [query here](https://app.redash.io/hasadna/queries/511391/source)
Road number changes - according to the newsflash road1 field. Also title changes accordingly.

**Additional context**
- Definition will be used by BE team to generate a Json response to FE
- Mock Json already exists in code (look for motorcycle_accidents_vs_all_accidents in [infographics_utils.py](https://github.com/hasadna/anyway/blob/dev/anyway/infographics_utils.py))
- Definition will be provided by Data team, after internal review
- Definition will be written in English and should use language agnostic definitions and data structures 
(e.g. SQL columns) as much as possible.

### PR DESCRIPTION
**Pull request by rsperer**
closes #1579

### CODE REVIEW

**Comment by rsperer** [comment]
triggering tests

**Comment by ziv17** [comment]
The query not-trivial. I think it should have tests.

**Review by ziv17 — APPROVED** [review]
Code is solid and tidy. I did not validated the logic correctness of the query.

**Comment by BarVolunteering** [comment]
Closing and reopening to restart the tests

**Review by BarVolunteering — APPROVED** [review]
Good!

**Pull request merged**
