### PR TITLE
Tokenize hebrew words as global constants

### PR DESCRIPTION
**Pull request by shakedzy**

### CODE REVIEW

**Comment by shakedzy** [comment]
@atalyaalon  I'd like to know your opinion about the way I implemented Hebrew words:
Every module will have to import `from anyway.language_constants import hebrew`

If the built-in words will be:
```
{"CHAIR": "כסא",
 "PLACE": "מקום"}
```
then in the code, all you have to do is use `hebrew.PLACE`

Also, I've added the option to easily add Hebrew prefixes:
```hebrew.CHAIR.THE => הכסא```
And you can add as many as you want:
```hebrew.CHAIR.THE.AND => והכסא```
and so:
```hebrew.concat(hebrew.CHAIR.THE, hebrew.PLACE.IN) => הכסא במקום```

**Comment by elazarg** [comment]
I don't like it.

This PR creates a DSL inside the project, one which is not obvious for readers (it is not what I would call "pythonic", more like Ruby), and would require constant mainainance. In particular, inheriting from `str` is odd. IMO it is more suitable to be developed as a 3rd party library, and adopted here after maturing.

Could you give more examples of concrete use cases inside the project, and explain why something simpler and more obvious, such as global constants, won't cut it?

**Comment by shakedzy** [comment]
@elazarg -  here's an example: כביש בינעירוני repeats in infographics_utils.py 4 times at different locations. Once `כביש בינעירוני` is added to `_WORDS`, it can be replaced by `hebrew.INTERCITY_ROAD`. That is much safer, and I think this is exactly what you mean by using global constants.

It seems the thing that alarms you is the `HebrewWord` class, that inherits from `str`. String is just another class, and there are locations in the code where the extra functionality is useful, see line 405 in `infographics_utils.py`. As `HebrewWord` inherits `str`, it really is just another string, with some extra options

**Comment by elazarg** [comment]
The first part of your answer is my question. You can simply use constants.

Regarding your reference, let's see. Currently it's:
```
" רחוב " + street1_hebrew + " ב" + yishuv_name
```

This can be replaces, very straightforwardly, with on of
```
f'רחוב {street1_hebrew} ב{yishuv_name}'
f'{hebrew.STREET} {street1_hebrew} ב{yishuv_name}'
f'{hebrew.STREET} {street1_hebrew} {hebrew.AT}{yishuv_name}'
f'{hebrew.STREET} {street1_hebrew} {hebrew.at(yishuv_name)}'
```
The version in your proposal is unclear to me, but I don't see a problem in any of the above examples that merits a dedicated DSL. And I believe a DSL should be justified by a long list of examples in order to be seriously considered.

**Comment by elazarg** [comment]
And regarding the use of `str`, yes it is just a class. A built in class which readers of the code have certain expectation about, and inheriting from it might break them. One example is a developer debugging the code using `if result is str: ...` which is nonstandard but something people do.

The default way of adding functionality to built in classes in python is using simple functions. I believe that deviating for this default requires very strong justification with many examples.

**Comment by elazarg** [comment]
Also, indeed there is a need for DSL, and that need arises from a single or small number of modules, it can be addressed using a tiny DSL (probably just a couple of functions and constants) inside that file of files.

**Comment by elazarg** [comment]
To summarize, I would expect your proposal to come in two phases, One that replace all Hebrew tokens with simple constants, and another that change all those constants to a DSL, while demonstrating both generalization capability and clear readability improvement.

**Comment by idosavion** [comment]
@shakedzy first of all, thanks for the PR! I'm with Elazar on this one, let's start with plain constants and think about the way we want to design the translation problem more thoroughly.

**Comment by shakedzy** [comment]
Hi @elazarg and @idosavion - I understand why this will make the code complex, and  I tend to agree with you. I would like to note that I was informed by Adi RH (which from some reason I cannot tag) that @atalyaalon mentioned we'll have to convert all Hebrew to English for the EU grant. Using this word API could make this much faster and bug-proof, as there will be not Hebrew letters scattered around the code at all.

**Comment by elazarg** [comment]
The last two examples I gave have no Hebrew letters in them either.

Additionally, I think we should distinguish between translation for UI and translation of other parts of the system. If some code handles a some external Hebrew API, translation does not make sense. It should also use constants, but these constants should be local to that module.

Also, constructing phrases programmatically for translation purposes will not work, IMO, given the infinite number of quirks in different languages. I would guess that we'll need constants for complete phrases.

**Comment by shakedzy** [comment]
Alright, I accept your opinion :)

**Pull request closed without merging**
