### PR TITLE
Age groups fix

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@aviklai can you check out the tests failure (it's a different one)? I assume it has something to do with the new age_groups fix

**Comment by atalyaalon** [comment]
@aviklai I don't think we need to update the test, I think that the test is OK and there is a problem with something along the way (I think it should be 1624)

**Comment by aviklai** [comment]
@atalyaalon But didn't you add the rsa markers? they are not supposed to change the total amount?

**Comment by atalyaalon** [comment]
@aviklai they do but not in that test:
Firstly, we don't load them in the test at all, secondly the test query contains "show_rsa"=False
screen shot 2018-10-01 at 13 37 44

**Pull request merged**
