### PR TITLE
fix-dockerignore

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@assafdayan even with this change, hasadna/anyway image is 1.47GB.
Do you see a way of reducing it further?

**Comment by atalyaalon** [comment]
@assafdayan for some reason I think that even with this change .git is not ignored. Does it make sense?

**Comment by assafdayan** [comment]
First this can be very easily tested.
Run the image with `docker run ... -i -t ... --entrypoint bash <image_name>`. Then, you'll have a shell active inside an image and you can check if something hogs space.
I believe the biggest issue is an underoptimized Dockerfile. At a glance, I noticed that it is based on `ubuntu:19.10` and then installs Python and VirtualEnv.
This is entirely unnecessary. We can base it on `python:3.7-slim-buster` (`slim` sheds away lots of non-necessities, while `buster` is the name of the latest stable Debian release).
VirtualEnv need not be installed, as there is little reason to separate runtime and dependencies on a dedicated instance. 
There is also no need to install `setuptools`, as they come pre-bundled with the correct repo.

Call/Zoom me if you'd like to have a more thorough discussion/session, I'll be happy to have one.

**Comment by atalyaalon** [comment]
@assafdayan @dimakuz 
So The image is still very large, partially due to .git file.
For some reason I still find the .git files when checking the content of the anyway container, running:
`docker exec -it anyway bash`
and then inside the container's shell:  `ls .git`
Did I write the dockerignore configuration in the wrong way? Why .git is not ignored?

Also, following @assafdayan's comment, I would be happy to rethink of the elements in our dockerfile and perhaps improve it as Assaf suggested. @dimakuz what do you think?

**Comment by dimakuz** [comment]
@atalyaalon I think you're seeing the `.git` because you're using the docker-compose setup, which overlays the repo on `/anyway` as a volume, shadowing what's actually in there.
I've tried this PR without the volume and `.git` and other ignored files are not there.

Re: image's big size - some things we should consider include:
* There's JDK installed at the moment which also pulls libllvm as dependency. I figure we might need JRE to run some java based stuff but having JDK seems a bit weird
* I agree with @assafdayan about virtualenv. We can base on a slimmer distro and pull most of the requirements from what is packaged in the distro. They'll probably be a bit slimmer (`numpy` in venv is built with tests and debuginfo).

**Pull request merged**
