### PR TITLE
Map controls css

### PR DESCRIPTION
**Pull request by LironRS**
Main Changes:
- Moved control buttons (CSV download, tour, link/embed map) to map view
- Changed order of rendering (search box in sync with controls)
- Moved the search box to the right
- Added Material Icons and FontAwesome stylesheets
- Changed calendar icon for "Time Sort" from png to font

**Rebased to upstream/dev**

### CODE REVIEW

**Comment by danielhers** [comment]
Please rebase to `dev` so we can merge this. If this was already merged to `master`, please close because we merged `master` to `dev` already.

**Comment by LironRS** [comment]
It was rebased to dev ("Rebased to upstream/dev") and was not merged to master, that's why it's on queue for the merge.

**Comment by danielhers** [comment]
Please rebase again, as dev has changed since.

**Comment by LironRS** [comment]
Sure, but before I push it I want to do a little QA and since both up-to-date master and dev give out the error below, then I can't check it until it is fixed.

"Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from clusters_calculator import retrieve_clusters
  File "/Users/lironshalev/anyway/clusters_calculator.py", line 5, in <module>
    import concurrent.futures
ImportError: No module named concurrent.futures"

**Comment by danielhers** [comment]
Did you run 'pip install -r requirements.txt' after updating?

**Comment by danielhers** [comment]
Needs rebasing to `dev` again, sorry.
Also, could you [squash](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html) your commits so that each commit is one whole coherent change?

**Pull request closed without merging**
