### PR TITLE
commit vehicles import

### PR DESCRIPTION
**Pull request by atalyaalon**
@shaysw - the vehicles import but fix - nice catch!

### CODE REVIEW

**Comment by atalyaalon** [comment]
@ziv17 FYI

**Comment by atalyaalon** [comment]
Added [an issue](https://github.com/hasadna/anyway/issues/1906) to make sure we will be alerted the next time it happens

**Comment by OriHoch** [comment]
@atalyaalon AFAIK this code is not running, the cbs import is handled from anyway-etl

**Comment by OriHoch** [comment]
I opened an issue to check why vehicles table is not being updated - #1909

**Comment by OriHoch** [comment]
code in anyway-etl was also fixed:
https://github.com/hasadna/anyway-etl/pull/5

**Pull request merged**
