### PR TITLE
modify to the correct expected location fields

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Comment by Mano3** [comment]
@atalyaalon 
Why was this merged without waiting for approval?
Does the algorithm outputs these results?
Are these what we want the algorithm to output, or what it really does?

**Comment by atalyaalon** [comment]
@Mano3 it's what the algorithm does, but in this case it seems like the location is indeed accurate. That's why it's merged. Tests are passing well in dev.

**Comment by elazarg** [comment]
It merely fixes a mistake I made due to google-maps issues on my machine.

**Comment by Mano3** [comment]
Alright, previous comments from other PRs confused me.

**Pull request merged**
