### PR TITLE
Change from sh to bash, as sh don't support pushd

### PR DESCRIPTION
**Pull request by BarVolunteering**
pushd is a bash enhancement and is not found in sh

### CODE REVIEW

**Comment by OriHoch** [comment]
Is this supposed to fix a specific error which you are seeing?

**Comment by BarVolunteering** [comment]
> 
> 
> Is this supposed to fix a specific error which you are seeing?

yes,
What i am experiencing is that the DB is empty after running `docker-compose up`
and in the `docker-compose up` log i see errors that are related to the restore_db.sh script.

Changing this line fixed it for me

**Comment by OriHoch** [comment]
the restore_db was working at least for me locally and in production, and I believe for other developers too

I looked at the code and it seems the pushd / popd may fail but that doesn't prevent  the restore

if you could post the errors you saw we could check what was the problem, could you try again?

I would rather not change the DB docker as it is currently running in production and it's better to keep production and dev the same

**Comment by BarVolunteering** [comment]
It won't reproduce - even after deleting all docker object and stating from fresh
@OriHoch Do you want me to test anything else before closing this pull?

**Comment by OriHoch** [comment]
thanks, so I will suggest not to fix it, and perhaps just keeping an issue open to remember this and maybe fix it in the future when we make some more changes to the db docker image

**Comment by atalyaalon** [comment]
@BarVolunteering can we close this one?

**Comment by BarVolunteering** [comment]
@atalyaalon Yes

**Pull request closed without merging**
