### PR TITLE
#51 - started to implement flask-security to enable roles + fixed the time of accidents in process.py.

### PR DESCRIPTION
**Pull request by aviklai**

### CODE REVIEW

**Comment by danielhers** [comment]
You have two commits with the same message. Please squash them.
What was wrong with the time calculation in `process.py`?
What is the advantage of flask-security over flask-login?

**Comment by aviklai** [comment]
@danielhers I squashed the commits.
About the time calculation in process.py - last week @galraij and me saw something strange with the time column in the acceidnets file. The value of the hours is between 1 to 96 and in process.py we just took the time and apllied on it mod 24. @galraij met with the Lamas and they explainded that the values 1 to 96 actually represent 15 minutes that start at 00:00 so 1 equals 00:00, 2 equals 00:15 and so on. That what I fixed in process.py.

Flask-Security - we want to implement an authentication and authorization system in ANYWAY. Flask-Login handles only login but doesn't handle roles. Flask-Security is a bundle of flask libraries that handle authentication and authorization, and it also includes Flask-Login.

**Comment by danielhers** [comment]
Thanks for the explanation about the time calculation. Could you add that as documentation?

**Comment by aviklai** [comment]
You mean inside the code?

**Comment by danielhers** [comment]
Yes, that would be a good place. Unless you want to create a new file
documenting the structure of the data files. But close to the calculation
in Python is a good idea.

**Comment by aviklai** [comment]
O.K, I added the documentation about the time calculation. 
About the documentation of the structure of the data files - it's already exists in the pdf files that come with each data file (it can be found in the folder of the full data from the Lamas).

**Comment by danielhers** [comment]
Right. Thanks :)

**Comment by aviklai** [comment]
@danielhers actually, we can add these pdf files to the data/lms folder in the project so every developer can see the data structure of the files. @galraij - is it ok? can we put the dictionary files here or Lamas forbids you from publishing them openly?

**Comment by danielhers** [comment]
Fine by me, if @galraij says it's ok

**Pull request merged**
