### PR TITLE
Use proper Python packaging (#722)

### PR DESCRIPTION
**Pull request by r-darwish**
I think this change is ready for testing. We no longer have import lines which are not allowed in Python 3, and all the needed commands are a part of `main.py`. I made sure that the unittest works and that the site itself performs a sanity check. I suggest deploying in Heroku and playing with it further

### CODE REVIEW

**Comment by danielhers** [comment]
Please also fix `Procfile` to fix Heroku deployment. Currently it's running the command `gunicorn main:app`.

**Comment by r-darwish** [comment]
Fixed. I also rebased it on the top of dev so it now contains Celery

**Comment by danielhers** [comment]
Sorry, please rebase again as I reverted the Celery merge due to the issues we had with it. Then I'll look at the review app again to make sure it works.

**Comment by r-darwish** [comment]
Done

**Comment by danielhers** [comment]
Looks good. Thanks!

**Comment by r-darwish** [comment]
@uda the cronjobs will need to be changed a bit after this is deployed. Can you please tell me which jobs do we have currently?

**Comment by uda** [comment]
@r-darwish Currently There are no jobs on the production server.
We need a crontab file to have all scripts that need to be run periodically.

**Comment by danielhers** [comment]
@uda I added a crontab to the DO server last November. It's the same as this: https://github.com/hasadna/anyway/blob/dev/crontab
@r-darwish please update the file above.

**Comment by uda** [comment]
@danielhers sorry, missed it

**Comment by simonaho** [comment]
Does this explain why we did not have data from Ihud Hazala?

**Comment by danielhers** [comment]
Why yes! I just looked at the inbox and they've been sending us a weekly
report since June.

**Comment by danielhers** [comment]
But it's an Excel file and we said we need to adjust the script to load it.
Have we done that?

**Comment by r-darwish** [comment]
@danielhers fixed the crontab file

**Pull request merged**
