### PR TITLE
#192 fix - Separating the description

### PR DESCRIPTION
**Pull request by omerxx**
Separated the description to separate entries in the DB, added them to the `marker` class in `process.py` and sent them as integers. 
The interpretation from integer to string is now done in `Marker.js` with the help of the new `localization.js` as a dictionary (previously used in `localization.py`)

### CODE REVIEW

**Comment by omerxx** [comment]
@galraij To my understanding accidents in freeways and intersections only have a junction name (`SHEM_ZOMET`) rather than an address, while urban accidents don't have that parameter but have an address. My fix is based on this assumption. 
Can you confirm this?

**Comment by danielhers** [comment]
Will merge after the critical period.

**Comment by omerxx** [comment]
Perfect thanks.
Once it's merged I'd like to work quickly on adding all other fields available in `localization` in separate fields too, so we can replicate the current behavior using separate fields for *every* field available.

**Comment by omerxx** [comment]
@danielhers I've changed the localize function as you requested.
Took care of marker.js indentation it looks okay now isn't it?
Anything else regarding this fix?

**Comment by danielhers** [comment]
There doesn't seem to be a problem. I think your last commit will simply be ignored when merging.
Your changes look fine, there are just still some indentation changes in `marker.js` (e.g. in `clickShare`).

Also, per https://github.com/samuelregev/anywayAndroidApp/issues/50, we should leave the `description` field in the DB and in `serialize` for now, and delete them later when the Android app supports the new format. So that's less code to delete, sorry ;)

**Comment by omerxx** [comment]
You're right about the indentation, but doesn't the change actually align better than the origin?
`clickShare` should be indented backwards to align with the other methods...

I'll have `description` brought back and commit again

**Comment by danielhers** [comment]
Sorry, you're right. You replaced tabs with spaces which is fine.

Thanks

**Comment by omerxx** [comment]
Regarding the description - replace it only in the DB, or does this require bringing `load_extra_data` back and the fields in `marker` class in `process.py`?

`marker.js` is irrelevant here right? I shouldn't bring it back there too...

**Comment by danielhers** [comment]
Right, you need to bring back the function that loads it.
Right again, in the client side only the new fields should be read.

**Comment by omerxx** [comment]
I think that does it :)

**Comment by samuelregev** [comment]
something went wrong
http://oway.org.il/markers?ne_lat=32.08599332534196&ne_lng=34.778186939656734&sw_lat=32.083670510194274&sw_lng=34.77612666785717&zoom=18&start_date=1356998400&end_date=1388448000&show_fatal=1&show_severe=1&show_light=1&show_inaccurate=0&format=

**Comment by omerxx** [comment]
It required rebuilding the DB. populating should take several hours

**Comment by danielhers** [comment]
Fixed

**Pull request merged**
