### PR TITLE
Age groups filter (fix #717)

### LINKED ISSUE #717: Add Age of accidents victims to filter
Add Age of accidents victims to filter and UI

### PR DESCRIPTION
**Pull request by r-darwish**
I went for the same UI that we have for other filters. I'm open to further suggestions.

### CODE REVIEW

**Comment by simonaho** [comment]
Looks good to me. Can you allow multiple selection of age groups?
@galraij what do you think?

**Comment by r-darwish** [comment]
Probably. It will need some more work, though.

**Comment by simonaho** [comment]
I think it is important to allow multiple selection so that people can choose the set of age groups for children, or elderly people, while still allowing narrow age segments. Thanks.

**Comment by r-darwish** [comment]
Implemented multiple selections. Should be updated in Heroku soon.

**Comment by simonaho** [comment]
Looks good! thank you! Will show to the Ministry of education next time we meet them, hopefully after the holidays.
@r-darwish @danielhers can be committed from my perspective.

**Pull request merged**
