### PR TITLE
Dependency upgrade

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by danielhers** [comment]
Currently abroad, won't have time until next Thursday...

Op vr 23 feb. 2018 16:37 schreef Roey Darwish Dror <notifications@github.com

**Comment by aviklai** [comment]
@r-darwish there is a problem in upgrading flask-admin and flask-security (flask login is redundant because it is installed with flask-security).
I tried to do that because I am working on the Admin panel and encountered an error regarding the integration with flask-babel:

https://github.com/mattupstate/flask-security/issues/715
https://github.com/mattupstate/flask-security/issues/718

**Comment by r-darwish** [comment]
@aviklai can you tell me how to reproduce the problem? I'll look for the latest version of Flask Security which doesn't cause problems

**Comment by aviklai** [comment]
@r-darwish try to ugrade the packeges and then go to:

http://localhost:5000/admin/login/

**Comment by r-darwish** [comment]
I now constrain flask login and flask security. The maximum recursion depth error doesn't happen anymore.

**Comment by aviklai** [comment]
What about flask admin? I tried to upgrade it to version 1.5 and got the recursion error.

**Comment by r-darwish** [comment]
That's weird. I'm using 1.5 as well and don't see this error. Can you give me the output of `pip list`?
Also, do you see this error when logged in to the control panel, or just in the panel's main page?

**Comment by aviklai** [comment]
pip list:

alembic (0.8.2)
amqp (2.2.2)
APScheduler (2.1.2)
astroid (1.6.0)
attrs (17.3.0)
Babel (2.5.0)
backports.functools-lru-cache (1.4)
billiard (3.5.0.3)
blinker (1.3)
celery (4.1.0)
certifi (2017.7.27.1)
chardet (3.0.4)
click (6.7)
colorama (0.3.9)
configparser (3.5.0)
enum34 (1.1.6)
et-xmlfile (1.0.1)
Flask (0.10.1)
Flask-Admin (1.5.0)
Flask-Assets (0.12)
Flask-Babel (0.11.2)
Flask-BabelEx (0.9.3)
Flask-Compress (1.3.0)
Flask-Login (0.3.2)
Flask-Mail (0.9.1)
Flask-Principal (0.4.0)
Flask-Security (1.7.5)
Flask-SQLAlchemy (2.1)
Flask-WTF (0.14.2)
funcsigs (1.0.2)
futures (2.1.6)
gunicorn (18.0)
idna (2.6)
isort (4.2.15)
itsdangerous (0.23)
jdcal (1.3)
Jinja2 (2.7.1)
kombu (4.1.0)
lazy-object-proxy (1.3.1)
Mako (1.0.7)
MarkupSafe (0.18)
mccabe (0.6.1)
newrelic (2.36.0.30)
openpyxl (2.4.9)
passlib (1.7.1)
pip (9.0.1)
pluggy (0.6.0)
psycopg2 (2.5.5)
py (1.5.2)
pylint (1.8.1)
pyproj (1.9.4)
pytest (3.3.1)
pytest-base-url (1.4.1)
pytest-html (1.16.0)
pytest-metadata (1.5.1)
pytest-selenium (1.11.3)
pytest-variables (1.7.0)
python-dateutil (2.4.2)
python-editor (1.0.3)
pytz (2017.2)
rauth (0.7.2)
redis (2.10.6)
requests (2.4.3)
selenium (3.8.0)
sendgrid (1.4.0)
setuptools (36.2.7)
singledispatch (3.4.0.3)
six (1.10.0)
smtpapi (0.2.0)
speaklater (1.3)
SQLAlchemy (1.1.14)
urllib3 (1.22)
URLObject (2.4.3)
vine (1.1.4)
webassets (0.10.1)
Werkzeug (0.14.1)
wheel (0.29.0)
wrapt (1.10.11)
WTForms (2.0.2)
yuicompressor (2.4.8)

and it happens when I am not logged in.

**Comment by r-darwish** [comment]
I installed the versions specified in your environment and I got the breakage too. It's caused by Flask-Babelex. For some reason, I didn't have it installed in my environment. When I uninstall it using pip the breakage was fixed.

I think that manually trying to upgrade Flask-Security for a version 3 pulled Flask-Babelex, which seems to break the environment even after Flask-Security is downgraded back to 2. Can you try to make a clean environment with the this branch and see if it works?

**Comment by aviklai** [comment]
You were right. When I uninstalled Babelex and installed Flask-Admin 1.5 it worked.

**Comment by aviklai** [comment]
And you can remove flask-login from the requirements because it is installed as part of flask-security.

**Comment by r-darwish** [comment]
We use flask login directly [here](https://github.com/hasadna/anyway/blob/dev/anyway/flask_app.py#L562) so I rather keep it.

**Comment by aviklai** [comment]
But it will still be available because it is installed automatically as part of Flask-Security.

**Comment by r-darwish** [comment]
I know, but I personally think it's not a good practice. I think that if we use something directly then we shouldn't rely on the fact that it's a dependency of another dependency.

**Comment by aviklai** [comment]
O.K - no problem. We can merge this.

**Pull request merged**
