### PR TITLE
feature 1506: Don't use cache for infographics data when testing locally

### LINKED ISSUE #1506: Don't use cache for infographics data when testing locally
In function get_infographics_data in infographics_utils, check FLASK_ENV var and if it's "development", call create_infographics_data(news_flash_id,years_ago) instead of using cache.

Motivation: we cannot test modification to existing APIs if cache is used

### PR DESCRIPTION
**Pull request by rsperer**
Closes #1506

### CODE REVIEW

**Review by BarVolunteering — APPROVED** [review]
Good Work!
Don't forget to squash the commits during the merge process.

**Review by BarVolunteering — APPROVED** [review]
Good Work!
If you can please un-black(un-format) the code sections that are not relevant for this issue
and don't forget to squash the commits during the merge process.

**Comment by ziv17** [comment]
The bypassing of cache access is well done.
Currently, whenever we are developing, cache will not work. We may want more granular setting (e.g. FLASK_ENV will be a list of values, that one of them will be 'bypass-cache').

**Review by ziv17 — APPROVED** [review]
The bypassing of cache access is well done.
Currently, whenever we are developing, cache will not work. We may want more granular setting (e.g. FLASK_ENV will be a list of values, that one of them will be 'bypass-cache').

**Comment by atalyaalon** [comment]
> The bypassing of cache access is well done.
> Currently, whenever we are developing, cache will not work. We may want more granular setting (e.g. FLASK_ENV will be a list of values, that one of them will be 'bypass-cache').

Since FLASK_ENV is a FLASK variable and not our own environment variable, I suggest we either use FLASK_ENV as is, or create our own var/s.  I suggest I'll merge this one so we can develop properly, and if there is a need we'll create our own vars instead.

**Pull request merged**
