### PR TITLE
WIP: Restructure code

### PR DESCRIPTION
**Pull request by uda**
Following #1009:
* Move functions and views into separate modules and files
* Make app more globally re-useable
* Create a centric server module for running the app

### CODE REVIEW

**Comment by elazarg** [comment]
Is there any way to revive this PR?

**Comment by atalyaalon** [comment]
@elazarg yes, but for that we need someone to own it, and @uda can't do it these days.

**Comment by uda** [comment]
I'll need to reboot in a new branch, I'll try to get to it and do it in portions so we it can survive the long run

**Comment by idosavion** [comment]
I took ownership on the issue, @uda  will glad to hear any thought you had / problem you've met while working on this issue.

**Pull request closed without merging**
