### PR TITLE
Fix black formatting

### PR DESCRIPTION
**Pull request by idosavion**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@idosavion how should we keep this formatting up to date?
Is there a command to format all changes locally? If so, please add it to the docs

**Comment by elazarg** [comment]
I'm sorry, @idosavion - I can't review such a project-wide change yet.

**Comment by atalyaalon** [comment]
@idosavion looks very good, please resolve conflicts / reformat files of current dev branch (not merging anything until we finish with this one).
Also perhaps modify documentation with explanation of installing test_requirements inside the docker and then running black inside the docker?

I believe this formatting can have a section of its own in the README. It's important since once these tests are inside, all volunteers will have to use this tool before pushing code.

Great work!

**Comment by idosavion** [comment]
@atalyaalon - ready for merge

**Pull request merged**
