### PR TITLE
Specify requirements version and sort.

### PR DESCRIPTION
**Pull request by idosavion**
Related issue: https://github.com/hasadna/anyway/issues/1257

### CODE REVIEW

**Comment by atalyaalon** [comment]
@idosavion please add the related issue to "linked issues" on the right sidebar

**Comment by idosavion** [comment]
@atalyaalon 
1. Fixed
2. I am not authorised to link issues to PR or vice versa.

**Comment by atalyaalon** [comment]
@idosavion you now have permission. Please try again.

**Comment by atalyaalon** [comment]
@idosavion also why didn't you fix all versions (for example, psycopg2, geoalchemy2, and a few others are not specified)

**Comment by idosavion** [comment]
I couldn't find the versions for some using pip freeze, also I don't fully understand the installation process of psycopg and would rather not touch it for now.

**Comment by elazarg** [comment]
Two versions are outdated:
* WTForms (2.2.1 instead of 2.3.1)
* beutifulsoup (4.6.0 instead of 4.9.1)
Is that intentional?

**Comment by isavion** [comment]
Yes, they were specified in the original file and I didn't want to create a breaking change.

**Pull request merged**
