### PR TITLE
Move DB restore to anyway image and stop building custom image for Postgres

### PR DESCRIPTION
**Pull request by dimakuz**
This patch shifts the DB restore process from DB build/startup into Anyway
image startup. This allows us to stop building a custom DB image.

This is partly motivated by effort to create a usable delelopment env on
kubernetes which does not take care of image building.

### CODE REVIEW

**Comment by atalyaalon** [comment]
@dimakuz PR Tests are not passing - can you take a look?

**Comment by dimakuz** [comment]
Still need to update docs, plus one major implication is that dump is downloaded on spinup vs build.
I can add a step to optionally download it during build for faster startup. @atalyaalon let me know what you think

**Comment by atalyaalon** [comment]
@dimakuz thanks. Updating the docs is very important.
Regarding your question, what do you think is best? Will the download occur every startup or only at the first one? (Every startup does not make sense...so I assume it should happen only at the first setup, and every time developers want to update the db)

**Comment by dimakuz** [comment]
@atalyaalon at the moment dump is never part of the image itself so it has to happen on (every) startup.
I can add an optional download step to image build (e.g. by passing build arg with file id) and then we would be able to build images containing the dump as well.
(But image will still download the dump if we're restoring and no local dump found - i.e. no build arg provided).

This way its possible to download only once when using docker-compose for development, but it is also possible to use same image in minikube where you can provide file id at deploy time and have a functional deployment without building custom image.

**Comment by atalyaalon** [comment]
@dimakuz why does it has to happen every startup? I mean there is a db volume...data is saved there.
Also - why not download dump only when RESTORE_DB is TRUE (I added this condition in the db dockerfile)

Since I'm not familiar with minikube, I'll let you and @OriHoch decide on this one. The important think on my part is: having an easy way to develop with recent data locally, moving to k8.

I also want to prepare up to date dumps. Also I think that the production dump's restore command AND the production db dump should be different than the ones for local development (right now it has the --no-owner flag in pg_restore, but I think that in production we need to make sure we insert the owners as well, and all of the permissions and users of the db)

**Comment by OriHoch** [comment]
The DB restore should be done on container startup and only if the DB is empty. This allows to use the same image for both dev and production. Also, for development/stage, if you ever need to get a fresh DB you can just delete the volume and restart the container.

The official postgres image supports initialization scripts, so you just put your restore script with .sh extension under `/docker-entrypoint-initdb.d/` - see the docs at https://hub.docker.com/_/postgres , not sure regarding the image you are using, but I assume it should support something like this as well.

**Comment by atalyaalon** [comment]
@OriHoch the docker-entrypoint-initdb.d was what we created... @dimakuz changed it in this pr, maybe we should stay with the current state?
How does it affect on k8?

**Comment by atalyaalon** [comment]
@OriHoch check out the files changed section 

Screen Shot 2020-06-02 at 19 31 11

**Comment by OriHoch** [comment]
yes, I missed that, it makes more sense to do the DB restore in the DB container

**Comment by OriHoch** [comment]
makes more sense to have it in the DB container and use the containers built-in init functionality

**Comment by atalyaalon** [comment]
@dimakuz @OriHoch Thanks.
What does this mean? Do I close this pr?

**Pull request closed without merging**
