### PR TITLE
Work around RSS issues: guid and date format

### LINKED ISSUE #1323: Walla RSS is inconsistent
When fetching RSS from the CI, we get items like this one:
```
<item>
    <title>123 בני אדם נדבקו בקורונה ביממה האחרונה</title>
    <link>https://news.walla.co.il/item/3365121</link>
    <description>&lt;p style="direction:rtl; clear:both"&gt;&lt;a href="https://news.walla.co.il/item/3365121"&gt;&lt;img hspace=5 border=0 align="right" src="https://img.wcdn.co.il/f_auto,t_18/2/9/7/9/2979578-46.jpg" /&gt;&lt;/a&gt; &lt;br/&gt; &lt;/p&gt;</description>
    <pubDate>Sat, 06 Jun 2020 11:39:00 +0300</pubDate>
</item>
```

But accessing it from a browser, you get this:
```
<item>
    <title><![CDATA[123 בני אדם נדבקו בקורונה ביממה האחרונה]]></title>
    <link>https://news.walla.co.il/break/3365121</link>
    <guid>https://news.walla.co.il/break/3365121</guid>
    <pubDate>Sat, 06 Jun 2020 08:39:00 GMT</pubDate>
    <description><![CDATA[<p style="direction:rtl; clear:both"><a href="https://news.walla.co.il/break/3365121"></a><br/>123 בני אדם נדבקו בקורונה ביממה האחרונה בישראל, כך הודיע היום (שבת) משרד הבריאות. זאת לאחר ש-16,133 בדיקות נערכו אתמול, המספר הגבוה ביותר מאז פרוץ המגיפה.</p>]]></description>
</item>
```

With a `guid` field, and different `pubDate` format.

### PR DESCRIPTION
**Pull request by elazarg**
Fix #1323.

Also, along the way, use port 443 directly, which saves two redirections and make things slightly faster.

I suggest merging this PR without squashing - each commit handles a different issue.

### CODE REVIEW

**Comment by atalyaalon** [comment]
@elazarg looks good!
@Mano3 @elashahar01 what do you think?

**Comment by elazarg** [comment]
Please wait - I'm working on making it more consistent, and unifying twitter's handling too.

**Comment by elazarg** [comment]
Ok @atalyaalon I think this is ready (conditioned on the tests). Note the incorrect time in the original tests 🤦 .

**Comment by elazarg** [comment]
We might want to consider using [pytz](https://pythonhosted.org/pytz/) or [dateparset](https://dateparser.readthedocs.io/en/latest).

**Comment by atalyaalon** [comment]
@elazarg looks very good! Great work! And good catch on the dates.
Do you want to use pytz or dateparser in this PR?

**Comment by elazarg** [comment]
@atalyaalon I think `pytz` can be deferred. It might be a better solution overall but currently we just need to fix the failing tests, and we can wait with adding yet another dependency.

**Comment by atalyaalon** [comment]
@elazarg Thanks!
Once @Mano3 approves, I'll merge

**Pull request merged**
