### PR TITLE
remove thread implementation for get infographics data

### PR DESCRIPTION
**Pull request by OriHoch**
(I didn't test it)

### CODE REVIEW

**Comment by atalyaalon** [comment]
@OriHoch I want to close this one without merging: we will start running this code once in a week or two for now, and later on we'll find another solution.
Any objections? Do you still see a problem if we run the code once a week or two?

**Comment by OriHoch** [comment]
well, current implementation is broken, you can't use threads, so I suggest to merge it even if you only run it a week or two

**Comment by atalyaalon** [comment]
> well, current implementation is broken, you can't use threads, so I suggest to merge it even if you only run it a week or two

@ziv17 what do you think?

**Comment by ziv17** [comment]
I think the question is how long do we plan to work without threads. As we do have performance issues, threads seems to me the most reasonable solution.

**Comment by OriHoch** [comment]
at the moment, the threads are not being used, so there is no change in performance from this PR, also as @atalyaalon said, you are only going to run it once every 1-2 weeks

regarding performance going forward, processing should be handled in the background, not inside the web process as is done here

**Comment by OriHoch** [comment]
in any case, the current implementation is broken and is most likely the cause of the problems we saw as I explained here - https://github.com/hasadna/anyway/issues/1410#issuecomment-676433197
so either need to fix it by making sure we use the driver in a way which supports multithreading, or merge this PR

**Pull request merged**
