### PR TITLE
Paginate the markers view

### PR DESCRIPTION
**Pull request by r-darwish**

### CODE REVIEW

**Comment by danielhers** [comment]
You can see the app here: https://anyway-unstable-pr-698.herokuapp.com/

**Comment by danielhers** [comment]
Sorry, I tried but I can't get this deployed on Heroku. It insists on using an old buildpack even though I keep changing it. Perhaps @uda could help with another service.

**Comment by danielhers** [comment]
Maybe with 16e5745 it will work. Please try merging to your branch.

**Comment by r-darwish** [comment]
Done

**Comment by danielhers** [comment]
It worked!

**Comment by simonaho** [comment]
Not sure if its ready yet, please let me know when I can see the work on the unstable site.
Also I see more than 3000 accidents on Seadia gaon st. while the stable site shows only 555, so I assume work under progress yet?

**Comment by danielhers** [comment]
You can see it here: https://anyway-unstable-pr-698.herokuapp.com/
Not sure why you see different numbers.
In any case, the "load more results" link should change the cursor when hovering over it. Also, it doesn't seem like the number of accidents at the top changes when more results are loaded, and there's no indication whether anything extra was actually loaded or everything is already there.

**Comment by r-darwish** [comment]
Agreed about the cursor. I'll fix that. Regarding the number shows at the top - it does change for me. The current number for accidents per page is 100 so you need an area with more than 100 accidents to see that it's working. When I zoom in on כיכר המדינה from cluster view into markers view I get 100 accidents and when I press the "more" button I get 150 (and the number on the top changes as well). Is there any specific area in which it doesn't work?

**Comment by simonaho** [comment]
Looks good :-) 
I see the total number being updated every time I press the show more results, up to 426, that is reasonable.
Can you remove this "show more results" button and bring the data automatically?
Then check what happened in the unstable branch why do we get there more than 3000 accidents on the Seadia Gaon st.?
thanks.

**Comment by danielhers** [comment]
Right, I guess I was just looking at a location that has less than 100 accidents.

**Comment by simonaho** [comment]
Checked it and the 3224 accidents bug when moving between dates and accidents list already appears in the production. Opened a separate bug.

**Comment by r-darwish** [comment]
Made the "entries per page" configurable in d5c07d5a8bdbf6b90fc32e47f549a6b9c08d3169. I'll squash this branch when we're ready to merge.

**Comment by r-darwish** [comment]
Removed the button. More results are now fetched automatically.

**Comment by danielhers** [comment]
No need to squash manually, github can now do it for you when merging the
PR.

**Comment by r-darwish** [comment]
It's okay. I reather do it manually so I can review the final commit and write a proper commit message.

**Comment by simonaho** [comment]
Looks great! Thanks for this amazing contribution through the weekend.
When you have time we can think what is the best way to improve clusters performance.
Did the old API for mobile and scripts remain the same' so it can continue working smoothly?

**Comment by r-darwish** [comment]
I'm glad I could help. The API should behave the same. Is it possible that one of the Android devlopers will check the application against my branch?

I squashed the commits and wrote a proper commit body. It's ready to merge unless there's an additional feedback.

**Comment by simonaho** [comment]
Great, go ahead and merge, I'll ask the android developer to check his code versus the unstable branch.

**Pull request merged**
