### PR TITLE
Added load_only to query for GPS to road segment

### PR DESCRIPTION
**Pull request by aentin16**
When pulling the road segment info from lat/lon coordinates, there are two relevant functions, get_db_matching_location_interurban and get_road_segment_id. The one causing the slow processing is the get_db_matching_location_interurban functions.

Within it, three lines are causing the most delay: the query to the database, and the addition of two new columsn with calculations.

This PR is an update to the query code so that it runs faster.

Of the rows that add columns, both would run faster if the table was shorter (it currently returns 2078 rows). As there are only 1006 segment (by the table on redash), perhaps this could be slimmed down either by a more complicated query or by limiting the year (eg from 2017 instead of 2014).

Finally, the slowest  part of the code by far is the calculation of the distance point and adding it to each row. If there is some way to make the geod.Inverse function more efficient, that would also help speed up the run.

### CODE REVIEW

**Comment by atalyaalon** [comment]
@aentin16 as discussed please make sure you use black for formatting

**Comment by aentin16** [comment]
Ignore this for now - it started throwing errors

**Comment by atalyaalon** [comment]
@aentin16 can I close this one?

**Comment by aentin16** [comment]
yes - closing

**Pull request closed without merging**
