### PR TITLE
#417 - Added basic chart to anyway. For now, it's only number of accidents in each month in the current frame.

### PR DESCRIPTION
**Pull request by aviklai**

### CODE REVIEW

**Comment by danielhers** [comment]
Wow, I didn't know you were working on this!

**Comment by danielhers** [comment]
Looks great, but please add a title to the plot so it's clear what it shows...
(Also, please try to use spaces rather than tab characters)

**Comment by aviklai** [comment]
Only in the last couple of days I had time to finish the basics :)

It's rudimentary but I think it has a great potential. Fo now it's just one chart but the idea is to enable the user to create different statistics with different parameters (that he can choose from a combobox, for example).

**Comment by aviklai** [comment]
@danielhers  Done.

**Pull request merged**
