### PR TITLE
#257 - uses rtree in sqlite and gist index in PostgreSQL in order to …

### PR DESCRIPTION
**Pull request by aviklai**
…make the queries faster.

I took @eladkarakuli code and adjusted it to the current dev version of anyway.
Needs to be tested further.
I have tested it with sqlite but it needs to be tested with PostgreSQL as well.

For windows users - pysqlite needs to be installed from here (the 32 bit version): http://www.lfd.uci.edu/~gohlke/pythonlibs/#pysqlite

### CODE REVIEW

**Comment by eladkarakuli** [comment]
Hi @aviklai , I've also written [tests](https://github.com/eladkarakuli/anyway/blob/257-postgis-rtree/tests/test_markerindex_provider.py), maybe you'll find them helpful

**Comment by aviklai** [comment]
@eladkarakuli Thanks - I saw them and I will add them. 
I have a problem with Travis that it doesn't recognize rtree module in sqlite, even though I added pysqlite which is an sqlite adapter for python that is compiled with the SQLITE_ENABLE_RTREE flag. It works on my local environment but Travis gives an error.
Anyway, it's much more important that it will work on PostgreSQL because it is the prod environment. 

Have any suggestions?

**Comment by danielhers** [comment]
It's saying there is a syntax error in `models.py`:

    (OperationalError) near "NOT": syntax error 'CREATE VIRTUAL TABLE IF NOT EXISTS marker_index USING rtree(id, minLng, maxLng, minLat, maxLat);' ()

Can you run `models.py` locally without the error?

**Comment by danielhers** [comment]
On Heroku with PostgreSQL it seems to fail for the same reason.

**Comment by danielhers** [comment]
@aviklai `libsqlite3-dev` is the package to install on Ubuntu. Please add it to `README.md`.

**Comment by danielhers** [comment]
I ran this on my computer with a PostgreSQL database as my `DATABASE_URL`, but I'm getting:

    sqlalchemy.exc.ProgrammingError: (ProgrammingError) type "geometry" does not exist
    LINE 4:  geom geometry(POINT,4326), 
                  ^
     '\nCREATE TABLE marker_index_gis (\n\tid SERIAL NOT NULL, \n\tgeom geometry(POINT,4326), \n\tPRIMARY KEY (id)\n)\n\n' {}

**Comment by danielhers** [comment]
I did some more research, and installed `postgis` on my Ubuntu (it wasn't installed), but it still didn't solve the problem because the DB must have the `postgis` extension installed. On Heroku this is done by running (as can be seen [here](https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search#requirements))

    heroku addons:create heroku-postgresql:standard-yanari

But it only works on production-tier plans. So it doesn't work...

**Comment by aviklai** [comment]
@danielhers So what do we do? If it wokrs only on production-tier plans and we can't have one, it won't help use because the Postgresql is the production db.

**Comment by danielhers** [comment]
Not sure. Need to see [here](https://devcenter.heroku.com/articles/heroku-postgres-extensions-postgis-full-text-search#provisioning) how to install it. I think we can install it on `anyway` (the production app) but it requires the app owner, so maybe @galraij can do it. On `anyway-unstable`, on the other hand, we'll need a production plan for the PostgreSQL add-on, but this will be a paid plan. I guess we could upgrade to a paid plan on the staging server. @galraij ?

**Comment by aviklai** [comment]
@danielhers I talked with Yehuda and we agreed that he and @omerxx will check the AWS option and then we will see how we will continue with this issue.

**Comment by danielhers** [comment]
Sure. Just keep the branch with these changes since they are quite important. Performance makes a difference for UX.

**Pull request closed without merging**
