### PR TITLE
#517 - added basic google login.

### PR DESCRIPTION
**Pull request by aviklai**
I have added a google app for ANYWAY and added basic google login to the application.

### CODE REVIEW

**Comment by danielhers** [comment]
Nice, thanks. Could you add the credentials to the Heroku apps please?

**Comment by aviklai** [comment]
Done.

**Comment by danielhers** [comment]
On anyway-unstable too?

**Comment by aviklai** [comment]
How can I access the unstable version in heroku? I can see there only the production version.

**Comment by danielhers** [comment]
Added you now.

**Comment by aviklai** [comment]
OK, I have added them to the unstable version as well.

**Comment by simonaho** [comment]
Great news!!!

**Pull request merged**
