### PR TITLE
Test precision, recall, and f1 for classifier

### PR DESCRIPTION
**Pull request by elazarg**
Add a new test that verifies a lower bound for the classifier, again based on the current statistics.

This PR adds a "corpus" in the form of the file `accidents_definitional_ynet.tsv` which is manually tagged by myself, by looking mostly at the results of the current classifier. The file can be read easily using any spreadsheet editor (such as google sheets).

Quoting the comment from the test:
>  The classification in the file is "definitional", meaning: We don't care if it is "about" an accident, but rather whether it us "THE report". In other words, is it the _first_ report about a _recent_ accident.

This is how I tagged the data, and I think this is the important property we need from the data. We don't really care about late updates, unless we want to update the information using pretty complex analysis regarding stuff like "the person injured last week died yesterday." It is not easy to distinguish definitional report from some other report, but it's possible - for example using ה הידיעה, which refers to known events.

### CODE REVIEW

**Comment by elazarg** [comment]
Here's a snippet of some reports that are currently considered to be accidents, along with my tagging.
image

**Comment by Mano3** [comment]
By the way, I think once the PR will be merged, a good follow up issue would be start improving these metrics by improving the classifiers. Although there are surely some other parts in the processing flow that are in worse shape than the classifiers (for example, matching the extracted, Google parsed, geographic location, to a textual representation in the DB)

**Comment by elazarg** [comment]
Extracted values to constants. I must say, though - I don't think it helps readability / maintainability.

**Comment by atalyaalon** [comment]
@elazarg great work!
Merging.

**Pull request merged**
