### PR TITLE
[docs] - Fix docker compose working directory instructions

### PR DESCRIPTION
**Pull request by Hedingber**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@Hedingber thinks this needs some improvement since it wasn't clear he needs to run it in the roof dir. @idosavion what do you think?

**Comment by idosavion** [comment]
Consider adding location relative to the docker-compose file (docker-compose.yml) since it is called with this parameter implicitly & squash 😄

**Review by idosavion — CHANGES_REQUESTED** [review]
Great work, one small general comment

**Review by ziv17 — APPROVED** [review]
Good correction.

**Comment by Hedingber** [comment]
@idosavion 
Did you mean to change it to something like: "Go to directory where the `docker-compose.yml` is and run" ?
If so, I can see the benefit - if we'll change the place where the file is located we won't need to change the docs, but TBH IMO it's just less user friendly like that 
anyways, you're the boss, let me know what you want and I'll add it

**Comment by idosavion** [comment]
Maybe as a comment in parentheses?

**Pull request merged**
