### PR TITLE
1009 general refactoring

### PR DESCRIPTION
**Pull request by idosavion**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@idosavion any news on this one?

**Comment by idosavion** [comment]
will try to finish by the end of the week

**Comment by idosavion** [comment]
@atalyaalon - What do you think about changing the url rules to something with a little bit more structure?
for example `/api/schools-yishuvs` -> `api/schools/yishuvs`

**Comment by atalyaalon** [comment]
> @atalyaalon - What do you think about changing the url rules to something with a little bit more structure?
> for example `/api/schools-yishuvs` -> `api/schools/yishuvs`

since it requires additional changes in other repos that use this API, I suggest we'll merge this PR, and later on decide on an API convention (for schools, and other reports such as the news flash report) - and then refactor urls.

**Comment by atalyaalon** [comment]
@ziv17 can you review this pr?

**Pull request merged**
