### PR TITLE
fix #246 To create RTree table, a spacial table for Marker Indexes.

### LINKED ISSUE #246: R*Tree Module for better quering performance
An R-Tree is a special index that is designed for doing range queries.
Use the module to index the queries of markers and highlights.

### PR DESCRIPTION
**Pull request by eladkarakuli**
First, create the table by an extended file with SQL command on models initialization. than wrapped insert and delete function at model level, implemented general insert and delete functions also at DB level, with tests. After marker processing, updating and populating the marker index table with all the markers that processed. Using marker index table when querying bounding boxes

### CODE REVIEW

**Comment by eladkarakuli** [comment]
It's working for me.
Maybe need to compile sqlite to enable RTree module? see [docs](https://www.sqlite.org/rtree.html)  - 2.0 Compiling The R*Tree Module

**Comment by danielhers** [comment]
The build failed: https://travis-ci.org/hasadna/anyway/builds/64047869
If it requires a special version of sqlite, it should be in the requirements. Should work on PostgreSQL?

**Comment by eladkarakuli** [comment]
ProstgerSQL uses different syntax to create the R-Tree table, which require changing `buildrtreeindex.sql`, or making a different file and making the code configurable.
About the failure, it seems that to enable SQLite RTree module, should compile sqlite3.c with the `SQLITE_ENABLE_RTREE=1` option, so I don't know if a change in requirements can fix the issue.
BTW, I didn't compile sqlite, and It's working for me.

**Comment by danielhers** [comment]
Please rebase from `dev` and also fix errors.

**Comment by omerxx** [comment]
@aviklai I remember we discussed this, can this be closed?

**Comment by aviklai** [comment]
@omerxx  Not yet. We will apply the fix after we migrate to Google Cloud

**Pull request closed without merging**
