### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by pint12**
fix of issue 184

### CODE REVIEW

**Comment by danielhers** [comment]
There are merge leftovers and conflict markers left. 
I suggest you sit with someone on Monday to open a PR properly.

**Comment by danielhers** [comment]
See my comment on #184.
(Also, it's good that you mention the issue in your commit message, but you should include the # sign before it so that it becomes linked to the issue on GitHub. Also, the commit message should be more informative and actually tell what you did in the commit and why).

**Comment by omerxx** [comment]
@pint12 would you like me to help you fix this PR and complete it?

**Comment by pint12** [comment]
Yes. It will make the things faster. I am on my way

**Comment by omerxx** [comment]
@pint12 @danielhers 
Closing the PR. Ilan will be working on this further and will open a better PR with improved when its ready.

**Pull request closed without merging**
