### PR TITLE
fix css class for walla

### PR DESCRIPTION
**Pull request by elazarg**
Seems like the css tag has changed. The older one returns empty collection.

BTW, should we really be swallowing Exception here? Without even logging it?

### CODE REVIEW

**Comment by atalyaalon** [comment]
@Mano3 do we have an open issue about this exception?
Perhaps we should add there this case of tag change, we want to fix it immediately. 
And perhaps even automate that fix?

**Comment by Mano3** [comment]
@elazarg You are right in both cases. 
This exception should be logged to the least.
Regarding what Atalya suggested, could you check if an automated fix could be devised? 
If not handling the exception should be a solid start.

**Comment by elazarg** [comment]
I'm not sure in what sense there can be an automated fix. I agree that we need a less brittle solution. For now I'd looking for `<a href="/break/\d+">` which I think should be more stable (and more obvious). But I'm not familiar with the format expected by the "client" code, so I tried changing as little as possible.

IMO the most robust approach would be to ask the Walla devs to add a dedicated, obvious class to the section to ease scraping.

**Comment by atalyaalon** [comment]
@elazarg right now talking with walla is not an option, in the future it will be.

**Comment by atalyaalon** [comment]
For now I think we can be satisfied with a way in which we can be notified if this class has changed - perhaps an email sent to us?

**Comment by elazarg** [comment]
I'm not sure how to add any active action such as sending an email without risking uncontrollable spam.
I also think that the news-flash scraping modules are in need of an extensive refactoring. Should I open an issue about that?

**Comment by atalyaalon** [comment]
OK, so I suggest writing a script that checks the news flash db, and if it doesn't have a new newsflash in x hours/days, we can send an email. We'll have to set this x to make sense (and maybe different per source?)
Regarding your second question please do open an issue.
Thanks!

**Comment by elazarg** [comment]
Ok. I think such a script should be proposed in an independent PR though.

**Comment by atalyaalon** [comment]
You are right, you can open a new issue for that.

**Pull request merged**
