### PR TITLE
[WIP] Add instruction for running on WSL

### PR DESCRIPTION
**Pull request by elazarg**
These instruction were tested by me, @asyaf and @elvirag. It is probably still not the best way to setup the project, but it works.

I tried to make the instructions as copy-pastable as possible. Any help in making it actually an executable script is welcome.

Also, Ubuntu 20.04 works well both on WSL and with docker on a VM.

### CODE REVIEW

**Comment by elvirag** [comment]
Cool.
Also, I can make it executable, no problem, just a couple of &&

**Comment by atalyaalon** [comment]
@elvirag any news on this one?
@elazarg @elvirag note that instructions has changed a bit since dump downloading with docker happens when creating the db container for the first time, using an .env file (see [this pr](https://github.com/hasadna/anyway/pull/1383)) - hence perhaps the wsl instructions and script will change a bit.

**Comment by elvirag** [comment]
> @elvirag any news on this one?
> @elazarg @elvirag note that instructions has changed a bit since dump downloading with docker happens when creating the db container for the first time, using an .env file (see [this pr](https://github.com/hasadna/anyway/pull/1383)) - hence perhaps the wsl instructions and script will change a bit.

Yes, I've worked on making it runnable, I was almost done,but having some trouble with the pg_dump file again (on a real ubuntu, actually)

**Comment by elazarg** [comment]
@Elvirag note that you don't have to use &&. There is a bash flag with an equivalent behavior.

**Comment by atalyaalon** [comment]
@elvirag how is it going? need any help with the pg_dump?

**Comment by BarVolunteering** [comment]
I am working with WSL2 - with no changes in the git for my setup(normal ubuntu setup)
From what I remember:
1.Installed WSL2 with Ubuntu 20.04
2.Installed Docker Desktop for windows
3.Changed the Docker Desktop settings to use WSL2

now I just run "docker-compose up" in windows cmd - and everything is running

**Comment by atalyaalon** [comment]
@carmelp16 please add instructions when using wsl2 - and ask from Bar and Ziv a review

**Comment by elazarg** [comment]
The idea was to have instructions that avoid using docker... oh well.

Is docker available for Windows versions other than proffesional?

**Comment by atalyaalon** [comment]
Yes, @carmelp16 can help you with this.
I think that the best practice will be using docker - so perhaps we should make sure we're creating a convenient doc for working with docker on windows with WSL2 and debugging with an IDE.

**Comment by BarVolunteering** [comment]
@elazarg  If your windows supports WSL2 then you can install docker for windows - so docker is available for most versions of windows .
You can read more about it here:
https://docs.docker.com/docker-for-windows/install-windows-home/

**Pull request closed without merging**
