### PR TITLE
Offset bug fix

### PR DESCRIPTION
**Pull request by atalyaalon**

### CODE REVIEW

**Review by BarVolunteering — APPROVED** [review]
Looks good!

**Comment by ziv17** [comment]
I wasn't aware that the order of adding elements to a query matters. Is it something different that I missed?

**Comment by BarVolunteering** [comment]
@ziv17 As far as i know there is no difference in the order of adding the elements to the query, here there is a case where this query is used in multiple cases and not all of them are require the `offset` parm.
Marked in red:
image

**Comment by atalyaalon** [comment]
@ziv17 closing this one without merging since issue is solved here
https://github.com/hasadna/anyway/pull/1765/files

**Pull request closed without merging**
