### PR TITLE
#769 - Removed manual date change..

### PR DESCRIPTION
**Pull request by aviklai**

### CODE REVIEW

**Comment by aviklai** [comment]
@simonaho I removed the option to edit the date manually.
Issue #769 occured because on each digit change, a reqest to the server was made and there is no guarantee which will return first (so we made request with invalid dates).

This fix assures that only when the date is change, only one request will be made.

**Comment by r-darwish** [comment]
This is a bit problematic for Firefox.

image

In Firefox, the date control isn't shown like in Chrome. There's just a textbox which you could edit. Now that manually editing is impossible, there's no way to change the filter in Firefox

**Comment by simonaho** [comment]
So is there a date wizard we can find without this bug? or do we need an if firefox :-( ?

**Comment by aviklai** [comment]
You are right. I will close this pull request and will implement a unified date picker that will look the same in all of the browsers.

**Pull request closed without merging**
