### PR TITLE
Feat 1221 import all road images from wikipedia

### PR DESCRIPTION
**Pull request by VickySidorkin**

### CODE REVIEW

**Comment by atalyaalon** [comment]
@VickySidorkin please run Black formatting so Black tests will pass, please fix

**Comment by atalyaalon** [comment]
@VickySidorkin weird, still fails, perhaps @idosavion can take a look?

**Comment by idosavion** [comment]
@VickySidorkin It seems like your branch in 31 commits behind `hasadna/dev` can you please rebase?

**Comment by atalyaalon** [comment]
@VickySidorkin can I merge this one?

**Comment by VickySidorkin** [comment]
@atalyaalon yes

**Comment by idosavion** [comment]
Can you please squash the commits before merging?

**Pull request merged**
